-- 백엔드와 프론트 모두 npm install 곡 해주세요!!!
CREATE TABLE IF NOT EXISTS `USER_MISTAKE_STATS` (
    `STAT_ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `USER_ID` BIGINT NOT NULL,
    `MISTAKE_TYPE` VARCHAR(255) NOT NULL COMMENT '실수 유형 (예: Magic Number)',
    `OCCURRENCE_COUNT` INT DEFAULT 0 COMMENT '누적 발생 횟수',
    `SOLVED_COUNT` INT DEFAULT 0 COMMENT '퀴즈 통과 횟수',
    `LAST_DETECTED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `LAST_REPORT_GENERATED_AT` DATETIME NULL,
    FOREIGN KEY (`USER_ID`) REFERENCES `USERS`(`USER_ID`) ON DELETE CASCADE,
    UNIQUE KEY `uk_user_mistake` (`USER_ID`, `MISTAKE_TYPE`)
) COMMENT = '사용자 실수 누적 통계';
ALTER TABLE USERS
ADD COLUMN MCP_TOKEN VARCHAR(255) NULL;
CREATE INDEX IDX_USERS_MCP_TOKEN ON USERS(MCP_TOKEN);